<?
  session_start();
	include("./config3.inc.php");
	include("./config2.inc.php");


  $anno  = $_POST['anno'];
  $mes   = $_POST['mes'];


        $sql2 = "
        DELETE
        FROM
        BIC_RELAC_COMUN_FT_CARGA_ORGS
        WHERE BIC_RELAC_COMUN_FT_CARGA_ORGS.ANNO=".$anno." AND BIC_RELAC_COMUN_FT_CARGA_ORGS.MES=".$mes."
        ;";


        $CONECT2 = mssql_connect(DB_HOST_2,DB_USER_2,DB_PASS_2);
        mssql_select_db(DB_DB_2);


        $result2 = mssql_query($sql2,$CONECT2); 


		$sql1 = "
    SELECT
        '".$anno."' AS ANNO,
        '".$mes."' AS MES,
        ORGANIZACION.ORG_CODIGO AS ORG_CODIGO,
        ORGANIZACION.UNI_CODIGO AS UNI_CODIGO,
        TIPO_ORGANIZACION.CORG_CODIGO AS CORG_CODIGO,
        REUNION.EST_CODIGO AS REST_CODIGO,
        REUNION.PRI_CODIGO AS RPRI_CODIGO,
        CASE WHEN (PROBLEMAS.TPRO_CODIGO IS NULL) THEN 0
        ELSE PROBLEMAS.TPRO_CODIGO
        END AS TPRO_CODIGO,
        CASE WHEN (PROBLEMAS.PRO_COMPROMISO IS NULL) THEN 2
        ELSE PROBLEMAS.PRO_COMPROMISO
        END AS PRO_COMPROMISO,
        CASE WHEN (COMPROMISO.COM_TERMINADA IS NULL) THEN 2
        ELSE COMPROMISO.COM_TERMINADA
        END AS COM_TERMINADA,
        CASE WHEN (COMPROMISO.COM_SOLUCIONOPROBLEMA IS NULL) THEN 2
        ELSE COMPROMISO.COM_SOLUCIONOPROBLEMA
        END AS COM_SOLUCIONOPROBLEMA,
        COUNT(REUNION.REU_CORRELATIVO) AS CANT_REUNIONES,
        COUNT(PROBLEMAS.PRO_CORRELATIVO) AS CANT_PROBLEMAS,
        COUNT(COMPROMISO.COM_ID) AS CANT_COMPROMISOS

    FROM ORGANIZACION

    INNER JOIN TIPO_ORGANIZACION ON
      (
        ORGANIZACION.TORG_CODIGO=TIPO_ORGANIZACION.TORG_CODIGO
        )

    INNER JOIN ORGANIZACION_ASISTENTE ON
      (
        ORGANIZACION.ORG_CODIGO=ORGANIZACION_ASISTENTE.ORG_CODIGO
        )

    INNER JOIN REUNION ON
      (
        ORGANIZACION_ASISTENTE.UNI_CODIGO=REUNION.UNI_CODIGO AND
          ORGANIZACION_ASISTENTE.REU_ANNO=REUNION.REU_ANNO AND
          ORGANIZACION_ASISTENTE.REU_CORRELATIVO=REUNION.REU_CORRELATIVO
            AND MONTH(REUNION.REU_FECHA)='".$mes."'
            AND YEAR(REUNION.REU_FECHA)='".$anno."'
        )

    LEFT JOIN PROBLEMAS ON
      (
        REUNION.UNI_CODIGO=PROBLEMAS.UNI_CODIGO AND
          REUNION.REU_ANNO=PROBLEMAS.REU_ANNO AND
          REUNION.REU_CORRELATIVO=PROBLEMAS.REU_CORRELATIVO
        )

    LEFT JOIN COMPROMISO ON
      (
        PROBLEMAS.UNI_CODIGO=COMPROMISO.UNI_CODIGO AND
          PROBLEMAS.REU_ANNO=COMPROMISO.REU_ANNO AND
          PROBLEMAS.REU_CORRELATIVO=COMPROMISO.REU_CORRELATIVO AND
            PROBLEMAS.PRO_CORRELATIVO=COMPROMISO.PRO_CORRELATIVO
        )

    GROUP BY
        ORGANIZACION.ORG_CODIGO,
        ORGANIZACION.UNI_CODIGO,
        TIPO_ORGANIZACION.CORG_CODIGO,
        REUNION.EST_CODIGO,
        REUNION.PRI_CODIGO,
        PROBLEMAS.TPRO_CODIGO,
        PROBLEMAS.PRO_COMPROMISO,
        COMPROMISO.COM_TERMINADA,
        COMPROMISO.COM_SOLUCIONOPROBLEMA
  ";



    $CONECT1 = @mysql_connect(DB_HOST_1,DB_USER_1,DB_PASS_1);
		mysql_select_db(DB_DB_1);


		$result1 = mysql_query($sql1,$CONECT1);


    $contador=0;


    while($myrow1 = mysql_fetch_array($result1))
    {

        $sql2 = "
        INSERT INTO
        BIC_RELAC_COMUN_FT_CARGA_ORGS
        (
        ANNO,
        MES,
        ORG_CODIGO,
        UNI_CODIGO,
        CORG_CODIGO,
        REST_CODIGO,
        RPRI_CODIGO,
        TPRO_CODIGO,
        PRO_COMPROMISO,
        COM_TERMINADA,
        COM_SOLUCIONOPROBLEMA,
        CANT_REUNIONES,
        CANT_PROBLEMAS,
        CANT_COMPROMISOS
        )
        VALUES
        (
        '".$myrow1[ANNO]."',
        '".$myrow1[MES]."',
        '".$myrow1[ORG_CODIGO]."',
        '".$myrow1[UNI_CODIGO]."',
        '".$myrow1[CORG_CODIGO]."',
        '".$myrow1[REST_CODIGO]."',
        '".$myrow1[RPRI_CODIGO]."',
        '".$myrow1[TPRO_CODIGO]."',
        '".$myrow1[PRO_COMPROMISO]."',
        '".$myrow1[COM_TERMINADA]."',
        '".$myrow1[COM_SOLUCIONOPROBLEMA]."',
        '".$myrow1[CANT_REUNIONES]."',
        '".$myrow1[CANT_PROBLEMAS]."',
        '".$myrow1[CANT_COMPROMISOS]."'
        )";


        $result2 = mssql_query($sql2,$CONECT2);


    $contador=$contador+1;

    }

    echo "CARGA ORGANIZACIONES MES ".$mes."-".$anno." FINALIZADA.  TOTAL REGISTROS: ".$contador;


?>









