
	<title>TOMA DE CONOCIMIENTO DE NUEVO PROCEDIMIENTO DE REGISTRO</title>

	<div style="width:960px; text-align: justify; text-justify: inter-word; padding:10px; font-family:Arial, Helvetica, sans-serif; font-size:13px; border-left: 8px solid ligth-blue; background-color:;">
		<h3 style="color:blue">SR(A). USUARIO PROSERVIPOL, <br></h3>
    <h3 style="color:green">SE COMUNICA QUE</h3>
		<p>
			PARA VUESTRO CONOCIMIENTO SE HA HABILITADO UN NUEVO PROCEDIMIENTO DE REGISTRO PARA DIFERENCIAR LOS DISTINTOS CASOS QUE HOY SE REGISTRAN COMO “COMISIÓN DE SERVICIO”. 
			DESDE AHORA EN ADELANTE, ANTES DE REGISTRAR UNA “COMISIÓN DE SERVICIO”, EL ENCARGADO DEL SISTEMA PROSERVIPOL DEBERÁ VERIFICAR SI SE TRATA DE UN CAMBIO DE CARGO O DE UN SERVICIO COMISIÓN DE SERVICIO POR DÍAS O UN SERVICIO COMISIÓN DE SERVICIO POR HORAS (INFERIOR A 24 HRS.). TENIENDO PRESENTE QUE EN CUALQUIERA DE LOS CASOS SEÑALADOS DEBERÁ CONTAR CON LA RESOLUCIÓN REGLAMENTARIA, LA CUAL DEBERÁ QUEDAR DISPONIBLE EN CASO DE CUALQUIER REVISIÓN QUE SE REALICE DE ESTAS CATEGORÍAS.
		</p>
		<p>
		PARA VER UN INSTRUCTIVO DE REGISTRO EN EL SISTEMA PROSERVIPOL DEL PERSONAL QUE SE ENCUENTRA EN COMISIÓN DE SERVICIO PRESIONE <A HREF="www.google.com">AQUÍ</A>
		</p>
		<p>
			ANTE REQUERIMIENTOS DE URGENCIA FAVOR TOMAR CONTACTO AL IP 20840.
		</p>
		<p>
			DEPARTAMENTO DE CONTROL DE GESTION Y SISTEMAS DE INFORMACION.
		</p>
	</div>		
