<?php
session_start();
if ($_SESSION["session_autent_p2"] == "SI")
{?>
<?php
  ini_set("memory_limit","80M");
  header("Content-type: application/vnd.ms-excel");
  header("Content-Disposition:attachment;  filename=\"PERSONAL_AGREGADO_".date('d_m_Y').".XLS\";");
	//header ('content-type: text/xml');
	include("./config1.inc.php");


    $fecha = date("Y-m-d");

		$sql1 = "
SELECT
IF
((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL AND UNIPADRE2.UNI_DESCRIPCION IS NULL AND UNIPADRE.UNI_DESCRIPCION IS NULL),
'',
IF
	((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL AND UNIPADRE2.UNI_DESCRIPCION IS NULL),
    UNIDAD.UNI_DESCRIPCION,
    IF
    	((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL),
        UNIPADRE.UNI_DESCRIPCION,
	    IF
    		((UNIPADRE4.UNI_DESCRIPCION IS NULL),
        	UNIPADRE2.UNI_DESCRIPCION,
            UNIPADRE3.UNI_DESCRIPCION
        	)
        )
    )
) AS ZONA,

IF
((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL AND UNIPADRE2.UNI_DESCRIPCION IS NULL AND UNIPADRE.UNI_DESCRIPCION IS NULL),
'',
IF
	((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL AND UNIPADRE2.UNI_DESCRIPCION IS NULL),
    '',
    IF
    	((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL),
        UNIDAD.UNI_DESCRIPCION,
	    IF
    		((UNIPADRE4.UNI_DESCRIPCION IS NULL),
        	UNIPADRE.UNI_DESCRIPCION,
            UNIPADRE2.UNI_DESCRIPCION
        	)
        )
    )
) AS PREFECTURA,

IF
((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL AND UNIPADRE2.UNI_DESCRIPCION IS NULL AND UNIPADRE.UNI_DESCRIPCION IS NULL),
'',
IF
	((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL AND UNIPADRE2.UNI_DESCRIPCION IS NULL),
    '',
    IF
    	((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL),
        '',
	    IF
    		((UNIPADRE4.UNI_DESCRIPCION IS NULL),
        	UNIDAD.UNI_DESCRIPCION,
            UNIPADRE.UNI_DESCRIPCION
        	)
        )
    )
) AS COMISARIA,

IF
((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL AND UNIPADRE2.UNI_DESCRIPCION IS NULL AND UNIPADRE.UNI_DESCRIPCION IS NULL),
'',
IF
	((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL AND UNIPADRE2.UNI_DESCRIPCION IS NULL),
    '',
    IF
    	((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL),
        '',
	    IF
    		((UNIPADRE4.UNI_DESCRIPCION IS NULL),
        	'',
            UNIDAD.UNI_DESCRIPCION
        	)
        )
    )
) AS DESTACAMENTO,

  CARGO_FUNCIONARIO.FUN_CODIGO AS CODIGO,
	GRADO.GRA_DESCRIPCION AS GRADO,
	FUNCIONARIO.FUN_APELLIDOPATERNO AS APELLIDO_PATERNO,
	FUNCIONARIO.FUN_APELLIDOMATERNO AS APELLIDO_MATERNO,
	FUNCIONARIO.FUN_NOMBRE AS NOMBRE,
    IF(UNIDAD2.UNI_DESCRIPCION IS NULL,'AGREGADO',UNIDAD2.UNI_DESCRIPCION) AS UNIDAD_AGREGADO,
    CARGO_FUNCIONARIO.FECHA_DESDE AS DESDE


FROM CARGO_FUNCIONARIO

    INNER JOIN FUNCIONARIO ON
    (CARGO_FUNCIONARIO.FUN_CODIGO=FUNCIONARIO.FUN_CODIGO)

	INNER JOIN GRADO ON
	(FUNCIONARIO.ESC_CODIGO=GRADO.ESC_CODIGO AND FUNCIONARIO.GRA_CODIGO=GRADO.GRA_CODIGO)

	INNER JOIN UNIDAD ON
    (CARGO_FUNCIONARIO.UNI_CODIGO = UNIDAD.UNI_CODIGO)

	LEFT JOIN UNIDAD AS UNIDAD2 ON
    (CARGO_FUNCIONARIO.UNI_AGREGADO = UNIDAD2.UNI_CODIGO)

LEFT JOIN UNIDAD AS UNIPADRE ON
(UNIPADRE.UNI_CODIGO=UNIDAD.UNI_PADRE)

LEFT JOIN UNIDAD AS UNIPADRE2 ON
(UNIPADRE2.UNI_CODIGO=UNIPADRE.UNI_PADRE)

LEFT JOIN UNIDAD AS UNIPADRE3 ON
(UNIPADRE3.UNI_CODIGO=UNIPADRE2.UNI_PADRE)

LEFT JOIN UNIDAD AS UNIPADRE4 ON
(UNIPADRE4.UNI_CODIGO=UNIPADRE3.UNI_PADRE)



WHERE
    (
    (
      CARGO_FUNCIONARIO.FECHA_DESDE <= '".$fecha."' AND
      CARGO_FUNCIONARIO.FECHA_HASTA > '".$fecha."'
    )
    OR
    (
       CARGO_FUNCIONARIO.FECHA_DESDE <= '".$fecha."' AND
       CARGO_FUNCIONARIO.FECHA_HASTA IS NULL AND
       FUNCIONARIO.UNI_CODIGO IS NOT NULL AND
       FUNCIONARIO.UNI_CODIGO = CARGO_FUNCIONARIO.UNI_CODIGO
    )
    )
    
    AND CARGO_FUNCIONARIO.CAR_CODIGO = 3000


ORDER BY
ZONA ASC,
PREFECTURA ASC,
COMISARIA ASC,
DESTACAMENTO ASC,
CARGO_FUNCIONARIO.FUN_CODIGO ASC;
";


    $CONECT1 = @mysql_connect(DB_HOST_1,DB_USER_1,DB_PASS_1);
    mysql_select_db(DB_DB_1);

		
		$result1 = mysql_query($sql1,$CONECT1);


    echo "<table border=1>";


    echo "<tr>
    <th>ZONA</th>
    <th>PREFECTURA</th>
    <th>COMISARIA</th>
    <th>UNIDAD</th>
    <th>CODIGO</th>
    <th>GRADO</th>
    <th>AP_PAT</th>
    <th>AP_MAT</th>
    <th>NOMBRE</th>
    <th>UNIDAD_AGREGADO</th>
    <th>DESDE</th>
    </tr>";


 
    while($myrow1 = mysql_fetch_array($result1))
    {
        echo "<tr>";
          echo "<td>".utf8_encode($myrow1[ZONA])."</td>";
          echo "<td>".utf8_encode($myrow1[PREFECTURA])."</td>";
          echo "<td>".utf8_encode($myrow1[COMISARIA])."</td>";
          echo "<td>".utf8_encode($myrow1[DESTACAMENTO])."</td>";
          echo "<td>".utf8_encode($myrow1[CODIGO])."</td>";
          echo "<td>".utf8_encode($myrow1[GRADO])."</td>";
          echo "<td>".utf8_encode($myrow1[APELLIDO_PATERNO])."</td>";
          echo "<td>".utf8_encode($myrow1[APELLIDO_MATERNO])."</td>";
          echo "<td>".utf8_encode($myrow1[NOMBRE])."</td>";
          echo "<td>".utf8_encode($myrow1[UNIDAD_AGREGADO])."</td>";
          echo "<td>".utf8_encode($myrow1[DESDE])."</td>";
        echo "</tr>";
    }



    mysql_close();





 echo "</table>";
?>

<?php
} else{ header("location: ../../index.php?ingreso=error2"); }
?>







