<?
  session_start();
	header ('content-type: text/xml');
	include("./config1.inc.php");


  $arregloUnidades  = str_replace(","," OR UNIDAD.UNI_CODIGO=",$_POST['arregloUnidades']);


		$sql1 = "
SELECT
IF
((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL AND UNIPADRE2.UNI_DESCRIPCION IS NULL AND UNIPADRE.UNI_DESCRIPCION IS NULL),
'',
IF
	((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL AND UNIPADRE2.UNI_DESCRIPCION IS NULL),
    UNIDAD.UNI_DESCRIPCION,
    IF
    	((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL),
        UNIPADRE.UNI_DESCRIPCION,
	    IF
    		((UNIPADRE4.UNI_DESCRIPCION IS NULL),
        	UNIPADRE2.UNI_DESCRIPCION,
            UNIPADRE3.UNI_DESCRIPCION
        	)
        )
    )
) AS ZONA,

IF
((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL AND UNIPADRE2.UNI_DESCRIPCION IS NULL AND UNIPADRE.UNI_DESCRIPCION IS NULL),
'',
IF
	((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL AND UNIPADRE2.UNI_DESCRIPCION IS NULL),
    '',
    IF
    	((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL),
        UNIDAD.UNI_DESCRIPCION,
	    IF
    		((UNIPADRE4.UNI_DESCRIPCION IS NULL),
        	UNIPADRE.UNI_DESCRIPCION,
            UNIPADRE2.UNI_DESCRIPCION
        	)
        )
    )
) AS PREFECTURA,

IF
((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL AND UNIPADRE2.UNI_DESCRIPCION IS NULL AND UNIPADRE.UNI_DESCRIPCION IS NULL),
'',
IF
	((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL AND UNIPADRE2.UNI_DESCRIPCION IS NULL),
    '',
    IF
    	((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL),
        '',
	    IF
    		((UNIPADRE4.UNI_DESCRIPCION IS NULL),
        	UNIDAD.UNI_DESCRIPCION,
            UNIPADRE.UNI_DESCRIPCION
        	)
        )
    )
) AS COMISARIA,

IF
((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL AND UNIPADRE2.UNI_DESCRIPCION IS NULL AND UNIPADRE.UNI_DESCRIPCION IS NULL),
'',
IF
	((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL AND UNIPADRE2.UNI_DESCRIPCION IS NULL),
    '',
    IF
    	((UNIPADRE4.UNI_DESCRIPCION IS NULL AND UNIPADRE3.UNI_DESCRIPCION IS NULL),
        '',
	    IF
    		((UNIPADRE4.UNI_DESCRIPCION IS NULL),
        	UNIDAD.UNI_DESCRIPCION,
            UNIDAD.UNI_DESCRIPCION
        	)
        )
    )
) AS DESTACAMENTO

FROM UNIDAD

LEFT JOIN UNIDAD AS UNIPADRE ON
(UNIPADRE.UNI_CODIGO=UNIDAD.UNI_PADRE)

LEFT JOIN UNIDAD AS UNIPADRE2 ON
(UNIPADRE2.UNI_CODIGO=UNIPADRE.UNI_PADRE)

LEFT JOIN UNIDAD AS UNIPADRE3 ON
(UNIPADRE3.UNI_CODIGO=UNIPADRE2.UNI_PADRE)

LEFT JOIN UNIDAD AS UNIPADRE4 ON
(UNIPADRE4.UNI_CODIGO=UNIPADRE3.UNI_PADRE)


WHERE UNIDAD.UNI_CODIGO = ".$arregloUnidades."

ORDER BY
ZONA ASC,
PREFECTURA ASC,
COMISARIA ASC,
DESTACAMENTO ASC";


    $CONECT1 = @mysql_connect(DB_HOST_1,DB_USER_1,DB_PASS_1);
		mysql_select_db(DB_DB_1);


		$result1 = mysql_query($sql1,$CONECT1);
 
    echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
    echo "<root>";

    while($myrow1 = mysql_fetch_array($result1))
    {
        echo "<unidad>";
          echo "<nombreZona>".utf8_encode($myrow1[ZONA])."</nombreZona>";
          echo "<nombrePrefectura>".utf8_encode($myrow1[PREFECTURA])."</nombrePrefectura>";
          echo "<nombreComisaria>".utf8_encode($myrow1[COMISARIA])."</nombreComisaria>";
          echo "<nombreUnidad>".utf8_encode($myrow1[DESTACAMENTO])."</nombreUnidad>";
        echo "</unidad>";
    }
    echo "</root>";


?>









