<?
include_once("../inc/config.inc.php");
include_once("conexion.Class.php");
//include("../../inc/configV4.inc.php");

Class dbResumenModuloValidacion extends Conexion{
	
	function resumnenDotacionPorUnidad($codigoUnidad, $fecha){

		$sql = "SELECT 
					TIPO_ESCALAFON.TESC_DESCRIPCION,
					COUNT(TIPO_ESCALAFON.TESC_DESCRIPCION) AS CANT_FUNCIONARIOS
				FROM FUNCIONARIO
				JOIN GRADO ON (FUNCIONARIO.ESC_CODIGO = GRADO.ESC_CODIGO) AND (FUNCIONARIO.GRA_CODIGO = GRADO.GRA_CODIGO)
				LEFT JOIN CARGO_FUNCIONARIO ON (FUNCIONARIO.FUN_CODIGO = CARGO_FUNCIONARIO.FUN_CODIGO)
				JOIN ESCALAFON ON (GRADO.ESC_CODIGO = ESCALAFON.ESC_CODIGO)
				JOIN TIPO_ESCALAFON ON (ESCALAFON.TESC_CODIGO = TIPO_ESCALAFON.TESC_CODIGO)
				WHERE CARGO_FUNCIONARIO.UNI_CODIGO = '".$codigoUnidad."' AND CARGO_FUNCIONARIO.FECHA_DESDE <= '".$fecha."' 
				AND (CARGO_FUNCIONARIO.FECHA_HASTA > '".$fecha."' OR CARGO_FUNCIONARIO.FECHA_HASTA IS NULL) 
				AND CARGO_FUNCIONARIO.CAR_CODIGO not in (1000, 2000, 3500)
				GROUP BY TIPO_ESCALAFON.TESC_DESCRIPCION
				ORDER BY TIPO_ESCALAFON.TESC_CODIGO";
		
		//echo $sql;
		$result = $this->execute($this->conect(),$sql);
		mysql_close();
		$listaResumenDotacion = array();
		$sinResumenDotacion = true;
		while($myrow = mysql_fetch_array($result)){
			array_push($listaResumenDotacion, array(
				"TIPO_ESCALAFON" 			=> utf8_encode($myrow["TESC_DESCRIPCION"]),
				"CANTIDAD_FUNCIONARIOS" 	=> $myrow["CANT_FUNCIONARIOS"]
			));
			if($myrow["EXISTE"]<>true) $sinResumenDotacion = false;
		}
		return $sinResumenDotacion ? array("data" => false) : array("data" => $listaResumenDotacion);

	}

	function resumnenDotacionAgregadaALaUnidad($codigoUnidad, $fecha){

		$sql = "SELECT
					TIPO_ESCALAFON.TESC_DESCRIPCION,
					UNIDAD.UNI_DESCRIPCION,
					COUNT(TIPO_ESCALAFON.TESC_DESCRIPCION) AS CANT_FUNCIONARIOS
				FROM GRADO
				JOIN FUNCIONARIO ON (GRADO.ESC_CODIGO = FUNCIONARIO.ESC_CODIGO) AND (GRADO.GRA_CODIGO = FUNCIONARIO.GRA_CODIGO)
				JOIN ESCALAFON ON (ESCALAFON.ESC_CODIGO = GRADO.ESC_CODIGO)
				JOIN TIPO_ESCALAFON ON (TIPO_ESCALAFON.TESC_CODIGO = ESCALAFON.TESC_CODIGO)
				LEFT JOIN CARGO_FUNCIONARIO ON (FUNCIONARIO.FUN_CODIGO = CARGO_FUNCIONARIO.FUN_CODIGO)
				LEFT JOIN CARGO ON (CARGO_FUNCIONARIO.CAR_CODIGO = CARGO.CAR_CODIGO)
				JOIN UNIDAD ON (CARGO_FUNCIONARIO.UNI_CODIGO = UNIDAD.UNI_CODIGO)
				WHERE ((CARGO_FUNCIONARIO.FECHA_DESDE <= '".$fecha."'
				AND CARGO_FUNCIONARIO.FECHA_HASTA > '".$fecha."')
				OR (CARGO_FUNCIONARIO.FECHA_DESDE <= '".$fecha."' AND CARGO_FUNCIONARIO.FECHA_HASTA IS NULL 
				AND FUNCIONARIO.UNI_CODIGO IS NOT NULL AND FUNCIONARIO.UNI_CODIGO = CARGO_FUNCIONARIO.UNI_CODIGO))
				AND CARGO_FUNCIONARIO.CAR_CODIGO IN (3000, 3001, 3002, 3003, 3004, 3005, 3006, 3100, 8520, 9340, 9350, 9360, 9370, 9380, 9390, 9400, 9410, 9420, 9430, 9440, 9460, 9840)
				AND CARGO_FUNCIONARIO.UNI_AGREGADO='".$codigoUnidad."'
				GROUP BY TIPO_ESCALAFON.TESC_CODIGO, CARGO_FUNCIONARIO.UNI_CODIGO
				ORDER BY TIPO_ESCALAFON.TESC_CODIGO ASC;";
		
		//echo $sql;
		$result = $this->execute($this->conect(),$sql);
		mysql_close();
		$listaResumenDotacion = array();
		$sinResumenDotacion = true;
		while($myrow = mysql_fetch_array($result)){
			array_push($listaResumenDotacion, array(
				"TIPO_ESCALAFON" 			=> utf8_encode($myrow["TESC_DESCRIPCION"]),
				"UNIDAD_ORIGEM" 			=> utf8_encode($myrow["UNI_DESCRIPCION"]),
				"CANTIDAD_FUNCIONARIOS" 	=> $myrow["CANT_FUNCIONARIOS"]

			));
			if($myrow["EXISTE"]<>true) $sinResumenDotacion = false;
		}
		return $sinResumenDotacion ? array("data" => false) : array("data" => $listaResumenDotacion);

	}

	function resumnenDotacionAgregadaAOtraUnidad($codigoUnidad, $fecha){

		$sql = "SELECT
					TIPO_ESCALAFON.TESC_DESCRIPCION,
					UNIDAD.UNI_DESCRIPCION,
					COUNT(TIPO_ESCALAFON.TESC_DESCRIPCION) AS CANT_FUNCIONARIOS,
					MIN(CARGO_FUNCIONARIO.CAR_CODIGO) AS MIN_CODIGO_CARGO
				FROM GRADO
				JOIN FUNCIONARIO ON (GRADO.ESC_CODIGO = FUNCIONARIO.ESC_CODIGO) AND (GRADO.GRA_CODIGO = FUNCIONARIO.GRA_CODIGO)
				JOIN ESCALAFON ON (ESCALAFON.ESC_CODIGO = GRADO.ESC_CODIGO)
				JOIN TIPO_ESCALAFON ON (TIPO_ESCALAFON.TESC_CODIGO = ESCALAFON.TESC_CODIGO)
				LEFT JOIN CARGO_FUNCIONARIO ON (FUNCIONARIO.FUN_CODIGO = CARGO_FUNCIONARIO.FUN_CODIGO)
				LEFT JOIN CARGO ON (CARGO_FUNCIONARIO.CAR_CODIGO = CARGO.CAR_CODIGO)
				LEFT JOIN UNIDAD ON (CARGO_FUNCIONARIO.UNI_AGREGADO = UNIDAD.UNI_CODIGO)
				WHERE CARGO_FUNCIONARIO.UNI_CODIGO = '".$codigoUnidad."' 
				AND ((CARGO_FUNCIONARIO.FECHA_DESDE <= '".$fecha."' AND CARGO_FUNCIONARIO.FECHA_HASTA > '".$fecha."')
				OR (CARGO_FUNCIONARIO.FECHA_DESDE <= '".$fecha."' AND CARGO_FUNCIONARIO.FECHA_HASTA IS NULL))
				AND CARGO_FUNCIONARIO.CAR_CODIGO IN (3000, 3001, 3002, 3003, 3004, 3005, 3006, 3100, 8520, 9340, 9350, 9360, 9370, 9380, 9390, 9400, 9410, 9420, 9430, 9440, 9460, 9840)
				GROUP BY TIPO_ESCALAFON.TESC_CODIGO, CARGO_FUNCIONARIO.UNI_AGREGADO
				ORDER BY TIPO_ESCALAFON.TESC_CODIGO ASC;";
		
		//echo $sql;
		$result = $this->execute($this->conect(),$sql);
		mysql_close();
		$listaResumenDotacion = array();
		$sinResumenDotacion = true;
		while($myrow = mysql_fetch_array($result)){
			array_push($listaResumenDotacion, array(
				"TIPO_ESCALAFON" 			=> utf8_encode($myrow["TESC_DESCRIPCION"]),
				"UNIDAD_DESTINO" 			=> utf8_encode($myrow["UNI_DESCRIPCION"]),
				"CANTIDAD_FUNCIONARIOS" 	=> $myrow["CANT_FUNCIONARIOS"],
				"MIN_CODIGO_CARGO" 			=> $myrow["MIN_CODIGO_CARGO"]

			));
			if($myrow["EXISTE"]<>true) $sinResumenDotacion = false;
		}
		return $sinResumenDotacion ? array("data" => false) : array("data" => $listaResumenDotacion);

	}

	function resumenDotacionNoOfertaPermanente($codigoUnidad, $fecha){

		$sql = "SELECT
					TIPO_ESCALAFON.TESC_DESCRIPCION,
					CARGO.CAR_DESCRIPCION,
					COUNT(TIPO_ESCALAFON.TESC_DESCRIPCION) AS CANT_FUNCIONARIOS
				FROM GRADO
				INNER JOIN FUNCIONARIO ON (GRADO.ESC_CODIGO = FUNCIONARIO.ESC_CODIGO)
				AND (GRADO.GRA_CODIGO = FUNCIONARIO.GRA_CODIGO)
				JOIN ESCALAFON ON (ESCALAFON.ESC_CODIGO = GRADO.ESC_CODIGO)
				JOIN TIPO_ESCALAFON ON (TIPO_ESCALAFON.TESC_CODIGO = ESCALAFON.TESC_CODIGO)
				LEFT JOIN CARGO_FUNCIONARIO ON (FUNCIONARIO.FUN_CODIGO = CARGO_FUNCIONARIO.FUN_CODIGO)
				LEFT JOIN CARGO ON (CARGO_FUNCIONARIO.CAR_CODIGO = CARGO.CAR_CODIGO)
				WHERE CARGO_FUNCIONARIO.UNI_CODIGO = '".$codigoUnidad."' AND
					((CARGO_FUNCIONARIO.FECHA_DESDE <= '".$fecha."' AND CARGO_FUNCIONARIO.FECHA_HASTA > '".$fecha."') 
					OR (CARGO_FUNCIONARIO.FECHA_DESDE <= '".$fecha."' AND CARGO_FUNCIONARIO.FECHA_HASTA IS NULL))
				AND CARGO_FUNCIONARIO.CAR_CODIGO IN (4000, 4100, 5000, 6000, 7010, 8400)
				GROUP BY TIPO_ESCALAFON.TESC_CODIGO, CARGO.CAR_DESCRIPCION
				ORDER BY TIPO_ESCALAFON.TESC_CODIGO ASC;";
		
		//echo $sql;
		$result = $this->execute($this->conect(),$sql);
		mysql_close();
		$listaResumenDotacion = array();
		$sinResumenDotacion = true;
		while($myrow = mysql_fetch_array($result)){
			array_push($listaResumenDotacion, array(
				"TIPO_ESCALAFON" 			=> utf8_encode($myrow["TESC_DESCRIPCION"]),
				"CARGO" 					=> utf8_encode($myrow["CAR_DESCRIPCION"]),
				"CANTIDAD_FUNCIONARIOS" 	=> $myrow["CANT_FUNCIONARIOS"]
			));
			if($myrow["EXISTE"]<>true) $sinResumenDotacion = false;
		}
		return $sinResumenDotacion ? array("data" => false) : array("data" => $listaResumenDotacion);

	}

	function personalSinServicioAsignado($codigoUnidad, $fecha){

		$sql = "(SELECT
					FUNCIONARIO.FUN_CODIGO AS FUN_CODIGO,
					GRADO.GRA_DESCRIPCION AS GRA_DESCRIPCION,
					FUNCIONARIO.FUN_APELLIDOPATERNO AS FUN_PRIMER_APELLIDO,
					FUNCIONARIO.FUN_APELLIDOMATERNO AS FUN_SEGUNDO_APELLIDO,
					FUNCIONARIO.FUN_NOMBRE AS FUN_NOMBRE,
				'FUNCIONARIO DE LA UNIDAD' AS SITUACION
				FROM FUNCIONARIO
				JOIN GRADO ON (FUNCIONARIO.ESC_CODIGO = GRADO.ESC_CODIGO) AND (FUNCIONARIO.GRA_CODIGO = GRADO.GRA_CODIGO)
				LEFT JOIN CARGO_FUNCIONARIO ON (FUNCIONARIO.FUN_CODIGO = CARGO_FUNCIONARIO.FUN_CODIGO)
				WHERE
					CARGO_FUNCIONARIO.UNI_CODIGO = '".$codigoUnidad."' 
					AND ((CARGO_FUNCIONARIO.FECHA_DESDE <= '".$fecha."' AND CARGO_FUNCIONARIO.FECHA_HASTA > '".$fecha."') 
					OR (CARGO_FUNCIONARIO.FECHA_DESDE <= '".$fecha."' AND CARGO_FUNCIONARIO.FECHA_HASTA IS NULL))
				AND CARGO_FUNCIONARIO.CAR_CODIGO NOT IN (1000, 2000, 3000, 3100, 3001, 3002, 3003, 3004, 3005, 4000, 4100, 5000, 6000, 7000, 7010, 6000, 7000, 8400, 3500, 3006, 8520,  9340, 9350, 9360, 9370, 9380, 9390, 9400, 9410, 9420, 9430, 9440, 9460, 9840)
				AND FUNCIONARIO.FUN_CODIGO NOT IN  (SELECT FUNCIONARIO_SERVICIO.FUN_CODIGO
													FROM FUNCIONARIO_SERVICIO
													JOIN SERVICIO ON (FUNCIONARIO_SERVICIO.UNI_CODIGO = SERVICIO.UNI_CODIGO) AND (FUNCIONARIO_SERVICIO.CORRELATIVO_SERVICIO = SERVICIO.CORRELATIVO_SERVICIO)
													JOIN TIPO_SERVICIO ON TIPO_SERVICIO.TSERV_CODIGO = SERVICIO.TSERV_CODIGO AND TIPO_SERVICIO.TSERV_GRUPO <> 'COLACION'
													WHERE SERVICIO.FECHA = '".$fecha."' AND SERVICIO.UNI_CODIGO = '".$codigoUnidad."'))
				UNION
				(SELECT
					FUNCIONARIO.FUN_CODIGO AS FUN_CODIGO,
					GRADO.GRA_DESCRIPCION AS GRA_DESCRIPCION,
					FUNCIONARIO.FUN_APELLIDOPATERNO AS FUN_PRIMER_APELLIDO,
					FUNCIONARIO.FUN_APELLIDOMATERNO AS FUN_SEGUNDO_APELLIDO,
					FUNCIONARIO.FUN_NOMBRE AS FUN_NOMBRE,
					'FUNCIONARIO AGREGADO A ESTA UNIDAD' AS SITUACION
				FROM FUNCIONARIO
				JOIN GRADO ON (FUNCIONARIO.ESC_CODIGO = GRADO.ESC_CODIGO) AND (FUNCIONARIO.GRA_CODIGO = GRADO.GRA_CODIGO)
				LEFT JOIN CARGO_FUNCIONARIO ON (FUNCIONARIO.FUN_CODIGO = CARGO_FUNCIONARIO.FUN_CODIGO)
				WHERE CARGO_FUNCIONARIO.UNI_AGREGADO = '".$codigoUnidad."' 
				AND CARGO_FUNCIONARIO.FECHA_DESDE <= '".$fecha."' AND (CARGO_FUNCIONARIO.FECHA_HASTA > '".$fecha."' OR CARGO_FUNCIONARIO.FECHA_HASTA IS NULL) 
				AND FUNCIONARIO.FUN_CODIGO NOT IN (SELECT FUNCIONARIO_SERVICIO.FUN_CODIGO
												FROM	FUNCIONARIO_SERVICIO
												JOIN SERVICIO ON (FUNCIONARIO_SERVICIO.UNI_CODIGO = SERVICIO.UNI_CODIGO) AND (FUNCIONARIO_SERVICIO.CORRELATIVO_SERVICIO = SERVICIO.CORRELATIVO_SERVICIO)
												JOIN TIPO_SERVICIO ON TIPO_SERVICIO.TSERV_CODIGO = SERVICIO.TSERV_CODIGO AND TIPO_SERVICIO.TSERV_GRUPO <> 'COLACION'
												WHERE SERVICIO.FECHA = '".$fecha."' AND SERVICIO.UNI_CODIGO = '".$codigoUnidad."'));";
		
		//echo $sql;
		$result = $this->execute($this->conect(),$sql);
		mysql_close();
		$listaResumenDotacion = array();
		$sinResumenDotacion = true;
		while($myrow = mysql_fetch_array($result)){
			array_push($listaResumenDotacion, array(
				"NOMBRE_FUNCIONARIO"		=> utf8_encode($myrow["FUN_PRIMER_APELLIDO"]) . " " . utf8_encode($myrow["FUN_SEGUNDO_APELLIDO"]) . ", " . utf8_encode($myrow["FUN_NOMBRE"]). " (" . utf8_encode($myrow["GRA_DESCRIPCION"]) . ")",
				"CODIGO_FUNCIONARIO"		=> $myrow["FUN_CODIGO"],
				"SITUACION_FUNCIONARIOS" 	=> $myrow["SITUACION"]
			));
			if($myrow["EXISTE"]<>true) $sinResumenDotacion = false;
		}
		return $sinResumenDotacion ? array("data" => false) : array("data" => $listaResumenDotacion);

	}

	function personalConMasDeUnServicioAsignado($codigoUnidad, $fecha){
		
		$sql = "SELECT
					FUNCIONARIO.FUN_CODIGO AS FUN_CODIGO,
					GRADO.GRA_DESCRIPCION AS GRA_DESCRIPCION,
					FUNCIONARIO.FUN_APELLIDOPATERNO AS FUN_PRIMER_APELLIDO,
					FUNCIONARIO.FUN_APELLIDOMATERNO AS FUN_SEGUNDO_APELLIDO,
					FUNCIONARIO.FUN_NOMBRE AS FUN_NOMBRE,
					SERVICIO.HORA_INICIO,
					SERVICIO.HORA_TERMINO,
					TIPO_SERVICIO.TSERV_DESCRIPCION,
					TIPO_SERVICIO.TSERV_TIPO,
					UNIDAD.UNI_ESPECIALIDAD,
					SERVICIO.TSERV_CODIGO
				FROM FUNCIONARIO
				JOIN GRADO ON (FUNCIONARIO.ESC_CODIGO = GRADO.ESC_CODIGO) AND (FUNCIONARIO.GRA_CODIGO = GRADO.GRA_CODIGO)
				LEFT JOIN CARGO_FUNCIONARIO ON (FUNCIONARIO.FUN_CODIGO = CARGO_FUNCIONARIO.FUN_CODIGO)
				JOIN FUNCIONARIO_SERVICIO ON (FUNCIONARIO.FUN_CODIGO = FUNCIONARIO_SERVICIO.FUN_CODIGO)
				JOIN SERVICIO ON (FUNCIONARIO_SERVICIO.UNI_CODIGO = SERVICIO.UNI_CODIGO) AND (FUNCIONARIO_SERVICIO.CORRELATIVO_SERVICIO = SERVICIO.CORRELATIVO_SERVICIO)
				JOIN TIPO_SERVICIO ON (SERVICIO.TSERV_CODIGO = TIPO_SERVICIO.TSERV_CODIGO)
				JOIN UNIDAD ON (UNIDAD.UNI_CODIGO = CARGO_FUNCIONARIO.UNI_CODIGO)
				WHERE CARGO_FUNCIONARIO.UNI_CODIGO = '".$codigoUnidad."'
				AND ((CARGO_FUNCIONARIO.FECHA_DESDE <= '".$fecha."' AND CARGO_FUNCIONARIO.FECHA_HASTA > '".$fecha."') OR
					(CARGO_FUNCIONARIO.FECHA_DESDE <= '".$fecha."' AND CARGO_FUNCIONARIO.FECHA_HASTA IS NULL))
				AND CARGO_FUNCIONARIO.CAR_CODIGO NOT IN (3000, 3100, 3001, 3002, 3003, 3004, 3005, 4000, 5000, 6000, 7010, 8400, 3006, 8520,  9340, 9350, 9360, 9370, 9380, 9390, 9400, 9410, 9420, 9430, 9440, 9460, 9840)					
				AND SERVICIO.FECHA = '".$fecha."' AND SERVICIO.UNI_CODIGO = '".$codigoUnidad."'
				AND EXISTS(
							SELECT FS2.FUN_CODIGO
							FROM FUNCIONARIO_SERVICIO FS2
							JOIN SERVICIO ON ( FS2.UNI_CODIGO = SERVICIO.UNI_CODIGO ) 
							AND (FS2.CORRELATIVO_SERVICIO = SERVICIO.CORRELATIVO_SERVICIO)
							WHERE SERVICIO.FECHA = '".$fecha."'
							AND SERVICIO.UNI_CODIGO = '".$codigoUnidad."'
							AND FS2.FUN_CODIGO = FUNCIONARIO.FUN_CODIGO
							GROUP BY FS2.FUN_CODIGO
							HAVING COUNT( FS2.FUN_CODIGO ) >1)
				ORDER BY
					FUNCIONARIO.FUN_APELLIDOPATERNO,
					FUNCIONARIO.FUN_APELLIDOMATERNO,
					FUNCIONARIO.FUN_NOMBRE,
					SERVICIO.HORA_INICIO;";
		
		//echo $sql;
		$result = $this->execute($this->conect(),$sql);
		mysql_close();
		$listaResumenDotacion = array();
		$sinResumenDotacion = true;
		while($myrow = mysql_fetch_array($result)){
			array_push($listaResumenDotacion, array(
				"NOMBRE_FUNCIONARIO"		=> utf8_encode($myrow["FUN_PRIMER_APELLIDO"]) . " " . utf8_encode($myrow["FUN_SEGUNDO_APELLIDO"]) . ", " . utf8_encode($myrow["FUN_NOMBRE"]) . " - " . utf8_encode($myrow["GRA_DESCRIPCION"]) . " - (" . $myrow["FUN_CODIGO"] . ")",
				"NOMBRE_SERVICIO"			=> utf8_encode($myrow["TSERV_DESCRIPCION"]),
				"CODIGO_SERVICIO"			=> $myrow["TSERV_CODIGO"],
				"TIPO_SERVICIO"				=> $myrow["TSERV_TIPO"],
				"HORA_INICIO"				=> $myrow["HORA_INICIO"],
				"HORA_TERMINO"				=> $myrow["HORA_TERMINO"],
				"UNIDAD_ESPECIALIDAD" 		=> $myrow["UNI_ESPECIALIDAD"]
			));
			if($myrow["EXISTE"]<>true) $sinResumenDotacion = false;
		}
		return $sinResumenDotacion ? array("data" => false) : array("data" => $listaResumenDotacion);

	}

	function tiemposDeServicioAsignadoPorFuncionario($codigoUnidad, $fecha){
		
		$sql = "SELECT 
					FUNCIONARIO_SERVICIO.FUN_CODIGO,
					FUNCIONARIO.FUN_APELLIDOPATERNO FUN_PRIMER_APELLIDO,
					FUNCIONARIO.FUN_APELLIDOMATERNO FUN_SEGUNDO_APELLIDO,
					FUNCIONARIO.FUN_NOMBRE,
					FUNCIONARIO.FUN_NOMBRE2,
					GRADO.GRA_DESCRIPCION,
					SUM(CASE
							WHEN SERVICIO.TSERV_CODIGO = 22  THEN IF(SERVICIO.HORA_TERMINO > SERVICIO.HORA_INICIO, IF(((TIME_TO_SEC(SERVICIO.HORA_TERMINO) - TIME_TO_SEC(SERVICIO.HORA_INICIO))/60) < 61,	((TIME_TO_SEC(SERVICIO.HORA_TERMINO) - TIME_TO_SEC(SERVICIO.HORA_INICIO))/60)+1440, ((TIME_TO_SEC(SERVICIO.HORA_TERMINO) - TIME_TO_SEC(SERVICIO.HORA_INICIO))/60)),(1440 - (TIME_TO_SEC(SERVICIO.HORA_INICIO) - TIME_TO_SEC(SERVICIO.HORA_TERMINO)) / 60))
							WHEN SERVICIO.TSERV_CODIGO = 23  THEN ((TIME_TO_SEC(SERVICIO.HORA_TERMINO)-TIME_TO_SEC(SERVICIO.HORA_INICIO))/60) + 1440
							WHEN SERVICIO.TSERV_CODIGO = 142 THEN -30
							WHEN SERVICIO.TSERV_CODIGO = 148 THEN -45
							WHEN SERVICIO.TSERV_CODIGO = 143 THEN -60
							WHEN SERVICIO.TSERV_CODIGO = 149 THEN -75
							WHEN SERVICIO.TSERV_CODIGO = 144 THEN -90
							WHEN SERVICIO.TSERV_CODIGO = 151 THEN -105
							WHEN SERVICIO.TSERV_CODIGO = 145 THEN -120
							WHEN SERVICIO.TSERV_CODIGO = 152 THEN -135
							WHEN SERVICIO.TSERV_CODIGO = 146 THEN -150
							WHEN SERVICIO.TSERV_CODIGO = 153 THEN -165
							WHEN SERVICIO.TSERV_CODIGO = 147 THEN -180
							WHEN SERVICIO.TSERV_CODIGO = 607 THEN 0
							ELSE IF(SERVICIO.HORA_TERMINO > SERVICIO.HORA_INICIO,((TIME_TO_SEC(SERVICIO.HORA_TERMINO) - TIME_TO_SEC(SERVICIO.HORA_INICIO)) / 60),(1440 - (TIME_TO_SEC(SERVICIO.HORA_INICIO) - TIME_TO_SEC(SERVICIO.HORA_TERMINO)) / 60))
					END) AS TIEMPO
				FROM FUNCIONARIO_SERVICIO
				JOIN SERVICIO ON (FUNCIONARIO_SERVICIO.UNI_CODIGO = SERVICIO.UNI_CODIGO) AND (FUNCIONARIO_SERVICIO.CORRELATIVO_SERVICIO = SERVICIO.CORRELATIVO_SERVICIO)
				JOIN TIPO_SERVICIO ON (SERVICIO.TSERV_CODIGO = TIPO_SERVICIO.TSERV_CODIGO)
				JOIN FUNCIONARIO ON (FUNCIONARIO_SERVICIO.FUN_CODIGO = FUNCIONARIO.FUN_CODIGO)
				JOIN GRADO ON (FUNCIONARIO.ESC_CODIGO = GRADO.ESC_CODIGO) AND (FUNCIONARIO.GRA_CODIGO = GRADO.GRA_CODIGO)
				WHERE SERVICIO.UNI_CODIGO = '".$codigoUnidad."' AND SERVICIO.FECHA = '".$fecha."' AND TIPO_SERVICIO.TSERV_TIPO <> 'N'
				GROUP BY
					FUNCIONARIO_SERVICIO.FUN_CODIGO,
					FUNCIONARIO.FUN_APELLIDOPATERNO,
					FUNCIONARIO.FUN_APELLIDOMATERNO,
					FUNCIONARIO.FUN_NOMBRE,
					FUNCIONARIO.FUN_NOMBRE2,
					GRADO.GRA_DESCRIPCION
				ORDER BY
					TIEMPO,
					FUNCIONARIO_SERVICIO.FUN_CODIGO";
		
		//echo $sql;
		$result = $this->execute($this->conect(),$sql);
		mysql_close();
		$listaResumenDotacion = array();
		$sinResumenDotacion = true;
		while($myrow = mysql_fetch_array($result)){

			$horasAsignadas	= floor($myrow[TIEMPO]/60) . " hora(s)";
  			if (($myrow[TIEMPO]%60) > 0) $horasAsignadas .= " con ".($myrow[TIEMPO]%60)." minuto(s)";

			array_push($listaResumenDotacion, array(
				"NOMBRE_FUNCIONARIO"		=> utf8_encode($myrow["FUN_PRIMER_APELLIDO"]) . " " . utf8_encode($myrow["FUN_SEGUNDO_APELLIDO"]) . ", " . utf8_encode($myrow["FUN_NOMBRE"]) . " - " . utf8_encode($myrow["GRA_DESCRIPCION"]) . " - (" . $myrow["FUN_CODIGO"] . ")",
				"TIEMPO_SERVICIO_MINUTGOS"	=> $myrow["TIEMPO"],
				"TIEMPO_SERVICIO"			=> $horasAsignadas
			));
			if($myrow["EXISTE"]<>true) $sinResumenDotacion = false;
		}
		return $sinResumenDotacion ? array("data" => false) : array("data" => $listaResumenDotacion);

	}

	function resumenMotivoDotacionNoOferta($codigoUnidad, $fecha){

		$sql = "SELECT 
					UCASE(TIPO_SERVICIO.TSERV_DESCRIPCION) AS TIPO,
					COUNT(FUNCIONARIO_SERVICIO.FUN_CODIGO) AS CANTIDAD
				FROM FUNCIONARIO_SERVICIO
				JOIN SERVICIO ON (FUNCIONARIO_SERVICIO.UNI_CODIGO = SERVICIO.UNI_CODIGO) AND (FUNCIONARIO_SERVICIO.CORRELATIVO_SERVICIO = SERVICIO.CORRELATIVO_SERVICIO)
				JOIN TIPO_SERVICIO ON (SERVICIO.TSERV_CODIGO = TIPO_SERVICIO.TSERV_CODIGO)
				WHERE SERVICIO.UNI_CODIGO = '".$codigoUnidad."' AND SERVICIO.FECHA = '".$fecha."' 
				AND TIPO_SERVICIO.TSERV_TIPO = 'N' AND SERVICIO.TSERV_CODIGO NOT IN (142, 143,144,145,146,147,148,149,151,152,153)
				GROUP BY TIPO_SERVICIO.TSERV_DESCRIPCION
				ORDER BY TIPO_SERVICIO.TSERV_DESCRIPCION";
		
		//echo $sql;
		$result = $this->execute($this->conect(),$sql);
		mysql_close();
		$listaResumenDotacion = array();
		$sinResumenDotacion = true;
		while($myrow = mysql_fetch_array($result)){
			array_push($listaResumenDotacion, array(
				"TIPO_SERVICIO" 			=> utf8_encode($myrow["TIPO"]),
				"CANTIDAD_FUNCIONARIOS" 	=> $myrow["CANTIDAD"]
			));
			if($myrow["EXISTE"]<>true) $sinResumenDotacion = false;
		}
		return $sinResumenDotacion ? array("data" => false) : array("data" => $listaResumenDotacion);

	}


}
