<?
// INICIO DE FUNCIONES

Class dbTipoServicio extends Conexion
{			
	function listaTipoServicio($especialidad, $grupo, $tipoServicios){
		
		//echo "ggg " . $especialidad . " ff";
		
		//if ($especialidad == "30"){
		// 
		// $sql = "SELECT 
		//		  ESPECIALIDAD_TSERVICIO.TIPO_SERVICIO AS TSERV_CODIGO,
		//		  TIPO_SERVICIO.TSERV_DESCRIPCION AS TSERV_DESCRIPCION,
		//		  TIPO_SERVICIO.TSERV_TIPO AS TSERV_TIPO,
		//		  ESPECIALIDAD_TSERVICIO.ACTIVO AS TSERV_ACTIVO
		//		FROM
		//		  ESPECIALIDAD_TSERVICIO
		//		  INNER JOIN TIPO_SERVICIO ON (ESPECIALIDAD_TSERVICIO.TIPO_SERVICIO = TIPO_SERVICIO.TSERV_CODIGO)
		//		WHERE
		//		  ESPECIALIDAD_TSERVICIO.UNIDAD_ESPECIALIDAD = 30 AND 
		//		  ESPECIALIDAD_TSERVICIO.ACTIVO = 1";
		// 
        //
	    // } else {
        //
		// 
		// $sql = "SELECT 
		//		  TIPO_SERVICIO.TSERV_CODIGO,
		//		  TIPO_SERVICIO.TSERV_DESCRIPCION,
		//		  TIPO_SERVICIO.TSERV_TIPO,
		//		  TIPO_SERVICIO.TSERV_ACTIVO
		//		 FROM
		//		  TIPO_SERVICIO
		//		 WHERE TIPO_SERVICIO.TSERV_ACTIVO = 1 ORDER BY TIPO_SERVICIO.TSERV_ORDEN";	     
	    // 
		//}
	     
	     
	     $sql = "SELECT 
				  ESPECIALIDAD_TSERVICIO.TIPO_SERVICIO AS TSERV_CODIGO,
				  TIPO_SERVICIO.TSERV_DESCRIPCION AS TSERV_DESCRIPCION,
				  TIPO_SERVICIO.TSERV_TIPO AS TSERV_TIPO,
				  ESPECIALIDAD_TSERVICIO.ACTIVO AS TSERV_ACTIVO
				FROM
				  ESPECIALIDAD_TSERVICIO
				  INNER JOIN TIPO_SERVICIO ON (ESPECIALIDAD_TSERVICIO.TIPO_SERVICIO = TIPO_SERVICIO.TSERV_CODIGO)
				WHERE
				  ESPECIALIDAD_TSERVICIO.UNIDAD_ESPECIALIDAD = ".$especialidad." AND 
				  ESPECIALIDAD_TSERVICIO.ACTIVO = 1 AND ESPECIALIDAD_TSERVICIO.TIPO = 'O' ORDER BY TSERV_DESCRIPCION";
		
		
		
		$sql = "SELECT 
				  ESPECIALIDAD_TSERVICIO.TIPO_SERVICIO AS TSERV_CODIGO,
				  TIPO_SERVICIO.TSERV_DESCRIPCION,
				  TIPO_SERVICIO.TSERV_TIPO,
				  ESPECIALIDAD_TSERVICIO.ACTIVO AS TSERV_ACTIVO
				FROM
				  ESPECIALIDAD_TSERVICIO
				  INNER JOIN TIPO_SERVICIO ON (ESPECIALIDAD_TSERVICIO.TIPO_SERVICIO = TIPO_SERVICIO.TSERV_CODIGO)
				WHERE
				  ESPECIALIDAD_TSERVICIO.UNIDAD_ESPECIALIDAD = ".$especialidad." AND 
				  ESPECIALIDAD_TSERVICIO.ACTIVO = 1 AND 
				  ESPECIALIDAD_TSERVICIO.TIPO = 'O' AND 
				  TIPO_SERVICIO.TSERV_GRUPO = '".$grupo."'
				ORDER BY TIPO_SERVICIO.TSERV_DESCRIPCION";
				  
		//if ($grupo == "COLACION") $sql .= "TIPO_SERVICIO.TSERV_ORDEN":
		//else $sql .= "TIPO_SERVICIO.TSERV_DESCRIPCION":
	     
	     //echo $sql;
	        				
		 $result = $this->execstmt($this->Conecta(),$sql);
		 mysql_close();
		 $i=0;
		 while($myrow = mysql_fetch_array($result)){
		 	$tipo = new tipoServicio;
		 	$tipo->setCodigo(STRTOUPPER($myrow["TSERV_CODIGO"]));
		 	$tipo->setDescripcion(STRTOUPPER($myrow["TSERV_DESCRIPCION"]));
		 	$tipo->setTipo(STRTOUPPER($myrow["TSERV_TIPO"]));
		 	$tipo->setActivo(STRTOUPPER($myrow["TSERV_ACTIVO"]));
		 	
		 	$tipoServicios[$i] = $tipo;
		 	$i++;
		 }
	}

}//end class   
?>