<?
  session_start();
	include("./config1.inc.php");
	include("./config2.inc.php");


  $anno  = $_POST['anno'];
  $mes   = $_POST['mes'];
  $dia   = $_POST['dia'];


        $CONECT2 = mssql_connect(DB_HOST_2,DB_USER_2,DB_PASS_2);
        mssql_select_db(DB_DB_2);

  if($dia==01)
  {

        $sql2 = "
        DELETE
        FROM
        BIC_PROSERVIPOL_FT_SERVICIOS
        WHERE YEAR(BIC_PROSERVIPOL_FT_SERVICIOS.FECHA_CODIGO)=".$anno." AND MONTH(BIC_PROSERVIPOL_FT_SERVICIOS.FECHA_CODIGO)=".$mes."
        ;";

        $result2 = mssql_query($sql2,$CONECT2); 
  }



		$sql1 = "
		SELECT
    SERVICIO.UNI_CODIGO AS UNI_CODIGO,

    '".$dia."-".$mes."-".$anno."' AS FECHA_CODIGO,

    SERVICIO.TSERV_CODIGO AS TSERV_CODIGO,
    
    CASE WHEN (FUNCIONARIO_SERVICIO.FACT_CODIGO IS NULL) THEN 0
    ELSE FUNCIONARIO_SERVICIO.FACT_CODIGO
    END AS FACT_CODIGO,

    CASE WHEN (CUADRANTE_SERVICIO.CUADRANTE_CODIGO IS NULL) THEN 0
    ELSE CUADRANTE_SERVICIO.CUADRANTE_CODIGO
    END AS UCUAD_CODIGO,

    FUNCIONARIO.ESC_CODIGO AS ESC_CODIGO,
    FUNCIONARIO.GRA_CODIGO AS GR_CODIGO,

    CASE WHEN (ARMA.TARM_CODIGO IS NULL) THEN 0
    ELSE ARMA.TARM_CODIGO
    END AS TARM_CODIGO,

    CASE WHEN (VEHICULO.TVEH_CODIGO IS NULL) THEN 0
    ELSE VEHICULO.TVEH_CODIGO
    END AS TVEH_CODIGO,

    CASE WHEN TIPO_SERVICIO.TSERV_TIPO = 'N' THEN 480
    ELSE
   	(
	    CASE WHEN SERVICIO.HORA_TERMINO > SERVICIO.HORA_INICIO
    	THEN CAST((TIME_TO_SEC(SERVICIO.HORA_TERMINO)-TIME_TO_SEC(SERVICIO.HORA_INICIO))/60 AS SIGNED)
	    ELSE CAST(1440-(TIME_TO_SEC(SERVICIO.HORA_INICIO)-TIME_TO_SEC(SERVICIO.HORA_TERMINO))/60 AS SIGNED)
	    END
	)
    END AS SERV_TOTALMINUTOS,

    COUNT(FUNCIONARIO_SERVICIO.UNI_CODIGO) AS SERV_CANTIDADCARABINEROS,
    COUNT(VEHICULO_SERVICIO.UNI_CODIGO) AS SERV_CANTIDADVEHICULOS,
    COUNT(ARMA_SERVICIO.UNI_CODIGO) AS SERV_CANTIDADARMAS,
    COUNT(ANIMAL_SERVICIO.UNI_CODIGO) AS SERV_CANTIDADANIMALES,
    SUM(VEHICULO_SERVICIO.KM_FINAL-VEHICULO_SERVICIO.KM_INICIAL) AS SERV_TOTALKM,
    NULL AS SERV_CANTIDADOTROCUADRANTE,
    NULL AS SERV_CANTIDADOTROCARGO

FROM
	SERVICIO
    INNER JOIN FUNCIONARIO_SERVICIO ON
    (
		SERVICIO.UNI_CODIGO=FUNCIONARIO_SERVICIO.UNI_CODIGO AND
    	SERVICIO.CORRELATIVO_SERVICIO=FUNCIONARIO_SERVICIO.CORRELATIVO_SERVICIO
    )
    LEFT JOIN CUADRANTE_SERVICIO ON
    (
		FUNCIONARIO_SERVICIO.UNI_CODIGO=CUADRANTE_SERVICIO.UNI_CODIGO AND
		FUNCIONARIO_SERVICIO.CORRELATIVO_SERVICIO=CUADRANTE_SERVICIO.CORRELATIVO_SERVICIO AND
  		FUNCIONARIO_SERVICIO.FUN_CODIGO=CUADRANTE_SERVICIO.FUN_CODIGO
    )
    INNER JOIN FUNCIONARIO ON
    (
		FUNCIONARIO_SERVICIO.FUN_CODIGO=FUNCIONARIO.FUN_CODIGO
    )
    LEFT JOIN ARMA_SERVICIO ON
    (
		FUNCIONARIO_SERVICIO.UNI_CODIGO=ARMA_SERVICIO.UNI_CODIGO AND
    	FUNCIONARIO_SERVICIO.CORRELATIVO_SERVICIO=ARMA_SERVICIO.CORRELATIVO_SERVICIO AND
    	FUNCIONARIO_SERVICIO.FUN_CODIGO=ARMA_SERVICIO.FUN_CODIGO
    )
    LEFT JOIN ARMA ON
    (
    	ARMA_SERVICIO.ARM_CODIGO=ARMA.ARM_CODIGO
    )
    LEFT JOIN FUNCIONARIO_VEHICULO ON
    (
		FUNCIONARIO_SERVICIO.UNI_CODIGO=FUNCIONARIO_VEHICULO.FUN_UNI_CODIGO AND
    	FUNCIONARIO_SERVICIO.CORRELATIVO_SERVICIO=FUNCIONARIO_VEHICULO.FUN_CORRELATIVO_SERVICIO AND
    	FUNCIONARIO_SERVICIO.FUN_CODIGO=FUNCIONARIO_VEHICULO.FUN_CODIGO
    )
    LEFT JOIN VEHICULO_SERVICIO ON
    (
		FUNCIONARIO_VEHICULO.VEH_UNI_CODIGO=VEHICULO_SERVICIO.UNI_CODIGO AND
    	FUNCIONARIO_VEHICULO.VEH_CORRELATIVO_SERVICIO=VEHICULO_SERVICIO.CORRELATIVO_SERVICIO AND
    	FUNCIONARIO_VEHICULO.VEH_CODIGO=VEHICULO_SERVICIO.VEH_CODIGO
    )
    LEFT JOIN VEHICULO ON
    (
		VEHICULO_SERVICIO.UNI_CODIGO=VEHICULO.VEH_CODIGO
    )
    LEFT JOIN ANIMAL_SERVICIO ON
    (
		FUNCIONARIO_SERVICIO.UNI_CODIGO=ANIMAL_SERVICIO.UNI_CODIGO AND
    	FUNCIONARIO_SERVICIO.CORRELATIVO_SERVICIO=ANIMAL_SERVICIO.CORRELATIVO_SERVICIO AND
    	FUNCIONARIO_SERVICIO.FUN_CODIGO=ANIMAL_SERVICIO.FUN_CODIGO
    )
    INNER JOIN TIPO_SERVICIO ON
    (
		SERVICIO.TSERV_CODIGO=TIPO_SERVICIO.TSERV_CODIGO
    )
    
    WHERE
    

    
    YEAR(SERVICIO.FECHA)=".$anno." AND MONTH(SERVICIO.FECHA)=".$mes." AND DAY(SERVICIO.FECHA)=".$dia."
    
    GROUP BY
    SERVICIO.UNI_CODIGO,
    SERVICIO.TSERV_CODIGO,
    FUNCIONARIO_SERVICIO.FACT_CODIGO,
    CUADRANTE_SERVICIO.CUADRANTE_CODIGO,
    FUNCIONARIO.ESC_CODIGO,
    FUNCIONARIO.GRA_CODIGO,
    ARMA.TARM_CODIGO,
    VEHICULO.TVEH_CODIGO
		";


    $CONECT1 = @mysql_connect(DB_HOST_1,DB_USER_1,DB_PASS_1);
		mysql_select_db(DB_DB_1);


		$result1 = mysql_query($sql1,$CONECT1);

 


    $contador=0;


    while($myrow1 = mysql_fetch_array($result1))
    {

        $sql2 = "
        INSERT INTO
        BIC_PROSERVIPOL_FT_SERVICIOS
        (
        UNI_CODIGO,
        FECHA_CODIGO,
        TSERV_CODIGO,
        FACT_CODIGO,
        UCUAD_CODIGO,
        ESC_CODIGO,
        GR_CODIGO,
        TARM_CODIGO,
        TVEH_CODIGO,
        SERV_TOTALMINUTOS,
        SERV_CANTIDADCARABINEROS,
        SERV_CANTIDADVEHICULOS,
        SERV_CANTIDADARMAS,
        SERV_CANTIDADANIMALES,
        SERV_TOTALKM,
        SERV_CANTIDADOTROCUADRANTE,
        SERV_CANTIDADOTROCARGO
        )
        VALUES
        (
        '".$myrow1[UNI_CODIGO]."',
        '".$myrow1[FECHA_CODIGO]."',
        '".$myrow1[TSERV_CODIGO]."',
        '".$myrow1[FACT_CODIGO]."',
        '".$myrow1[UCUAD_CODIGO]."',
        '".$myrow1[ESC_CODIGO]."',
        '".$myrow1[GR_CODIGO]."',
        '".$myrow1[TARM_CODIGO]."',
        '".$myrow1[TVEH_CODIGO]."',
        '".$myrow1[SERV_TOTALMINUTOS]."',
        '".$myrow1[SERV_CANTIDADCARABINEROS]."',
        '".$myrow1[SERV_CANTIDADVEHICULOS]."',
        '".$myrow1[SERV_CANTIDADARMAS]."',
        '".$myrow1[SERV_CANTIDADANIMALES]."',
        '".$myrow1[SERV_TOTALKM]."',
        '".$myrow1[SERV_CANTIDADOTROCUADRANTE]."',
        '".$myrow1[SERV_CANTIDADOTROCARGO]."'
        )";


        $result2 = mssql_query($sql2,$CONECT2);


    $contador=$contador+1;

    }

    echo "CARGA SERVICIOS DIA ".$dia."-".$mes."-".$anno." FINALIZADA.  TOTAL REGISTROS: ".$contador;
        
//    echo "CARGA SERVICIOS FINALIZADA.  TOTAL REGISTROS: ";
?>









